# Generated by Django 6.0.2 on 2026-02-05 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterthumbnail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chapterthumbnail',
            name='page',
        ),
        migrations.AddField(
            model_name='arcdetailpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='chapterpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.DeleteModel(
            name='ArcThumbnail',
        ),
        migrations.DeleteModel(
            name='ChapterThumbnail',
        ),
    ]
