# Generated by Django 6.0.2 on 2026-02-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_remove_chapterthumbnail_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcdetailpage',
            name='arc_number',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcdetailpage',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='chapterpage',
            name='chapter_number',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
