# Generated by Django 6.0.2 on 2026-02-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_arcdetailpage_arc_number_arcdetailpage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcindexpage',
            name='readers_note',
            field=models.TextField(default='Arc disarankan dibaca secara berurutan untuk mendapatkan pengalaman cerita yang utuh. Beberapa detail kecil di awal akan memiliki dampak besar di arc berikutnya.'),
        ),
    ]
