# Generated by Django 6.0.2 on 2026-02-15 11:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='social_media',
            field=wagtail.fields.StreamField([('social', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('x', 'X'), ('instagram', 'Instagram'), ('threads', 'Threads')]}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('provider', 0), ('url', 1)]], {})}),
        ),
    ]
