# Generated by Django 6.0.2 on 2026-02-03 23:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(default='home'),
            preserve_default=False,
        ),
    ]
