# Generated by Django 6.0.2 on 2026-02-04 12:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
