# Generated by Django 6.0.2 on 2026-02-09 06:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='quote',
            field=wagtail.fields.StreamField([('quote', 2)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Quote'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Author', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('quote', 0), ('author', 1)]], {})}),
        ),
    ]
