# Generated by Django 6.0.2 on 2026-02-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='quote',
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_text',
            field=models.TextField(blank=True),
        ),
    ]
