# Generated by Django 6.0.2 on 2026-02-09 07:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_quote_homepage_quote_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='genres',
            field=wagtail.fields.StreamField([('genre', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Genre'})}),
        ),
    ]
